@startuml

interface IView
    abstract ViewBase
        class Rect
        class SimpleText
            class TextButton
        class Image
    abstract SwingView
        class SwingRect
        class SwingSimpleText
        class SwingTextButton
        class SwingImage

class LineProperties

IView <|-- ViewBase
ViewBase <|-- Rect
ViewBase <|-- SimpleText
ViewBase <|-- Image

SimpleText <|-- TextButton

IView <|-- SwingView
SwingView <|-- SwingRect
SwingView <|-- SwingSimpleText
SwingView <|-- SwingTextButton
SwingView <|-- SwingImage

Rect <.. SwingRect
SimpleText <.. SwingSimpleText
TextButton <.. SwingTextButton
Image <.. SwingImage

@enduml